# Introduction to TensorFlow2.

<table class="tfo-notebook-buttons" align="left">
  <td>
    <a target="_blank" href="https://colab.research.google.com/github/taipeitechmmslab/MMSLAB-TF2/blob/master/Lab1.ipynb"><img src="https://www.tensorflow.org/images/colab_logo_32px.png" />Run in Google Colab</a>
  </td>
  <td>
    <a target="_blank" href="https://github.com/taipeitechmmslab/MMSLAB-TF2/blob/master/Lab1.ipynb"><img src="https://www.tensorflow.org/images/GitHub-Mark-32px.png" />View source on GitHub</a>
  </td>
</table>

In [35]:
import tensorflow as tf

1.2. Introduction to TensorFlow
Tensor

In [42]:
#Create a “scalar” tensor (a tensor with no “axes”)
x1 = tf.constant(5) # dtype=int32 (default)
print(x1) # Display x1


tf.Tensor(5, shape=(), dtype=int32)


In [44]:
#Create a “vector” tensor (a tensor has 1-axis):
x2 = tf.constant([1.0, 2.0, 6.0]) # dtype= float32
print(x2) # Display x2

tf.Tensor([1. 2. 6.], shape=(3,), dtype=float32)


In [47]:
#Create a “maxtrix” tensor (a tensor has 2-axes)
x3 = tf.constant([[1, 8],
                  [2, 5],
                  [4, 4]], 
                  dtype=tf.float64)
print(x3) # Display x3

tf.Tensor(
[[1. 8.]
 [2. 5.]
 [4. 4.]], shape=(3, 2), dtype=float64)


In [50]:
#Create a 3-axes tensor with shape: [3, 2, 4]
x4 = tf.constant ([[[1, 1, 2, 2],
                    [3, 3, 4, 4]],
                    [[5, 5, 6, 6],
                    [7, 7, 8, 8]],
                    [[9, 9, 0, 0],
                    [1, 1, 3, 3]],])
print(x4) # Display x4


tf.Tensor(
[[[1 1 2 2]
  [3 3 4 4]]

 [[5 5 6 6]
  [7 7 8 8]]

 [[9 9 0 0]
  [1 1 3 3]]], shape=(3, 2, 4), dtype=int32)


Flow:  refers to a computational graph. 

In [58]:
#using Tensorflow to present the mathematical formula Y = (a + b)/(a-b). 

a = tf.constant(4, name='a')  # a = 4
b = tf.constant(2, name='b')  # b = 2
c = tf.add (a, b, name='c')  # a + b
d = tf.subtract (a, b, name='c')  # a - b 
Y = tf.divide (c, d, name='Y')  # c/d 
print("Y =", Y) # Display Y

Y = tf.Tensor(3.0, shape=(), dtype=float64)


---
## Eager Execution

**Important features of Eager Execution are listed as below:**

- Immediate evaluation of operations. 
- Easier debugging program.
- No need to construct the computational graph.
- The calculation result can be returned without tf.Session.run.


**Comparisons between TensorFlow1.x and TensorFlow2.0**
```
TensorFlow 1.x code:
>>> a = tf.constant(1)
>>> print(a)
Tensor("Const_5:0", shape=(), dtype=int32)

>>> sess = tf.Session()
>>> print("a = {}".format(sess.run(a)))
a = 1


TensorFlow 2.0 code:
>>> a = tf.constant(1)
>>> print(a)
tf.Tensor(1, shape=(), dtype=int32)
```

**Basic TensorFlow Operations**

Step1: Import necessary packages     

In [59]:
import numpy as np  # import Numpy library
import tensorflow as tf  # import TensorFlow library
# check if Eager Execution is activated
print("Eager Execution is activated: {}".format(tf.executing_eagerly()))

Eager Execution is activated: True


Step 2: Create a constant Tensor

In [60]:
a = tf.constant(3)    # create a constant tensor with value of 3
b = tf.constant(4)    # create a constant tensor with value of 4
# display Tensor values
print("a = {}".format(a))
print("b = {}".format(b))

a = 3
b = 4


Step 3: Check the data type of a tensor

In [61]:
print(a)    # shape=() means “a” is a scalar, and dtype=int32 means “a” is an integer. 
print(b)    # shape=() means “b” is a scalar, and dtype=int32 means “b” is an integer. 

tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor(4, shape=(), dtype=int32)


Step 4: Use the addition and multiplication operations     

In [62]:
c = a + b
print("a + b = {}".format(c))    # show the result of a+b
d = a * b
print("a * b = {}".format(d))    # show the result of a*b

a + b = 7
a * b = 12


Step 5: Create two-dimensional Tensors. 

In [63]:
# Create a 2D Tensor whose dtype is float32
a = tf.constant([[1., 2.], [3., 4.]], dtype=tf.float32)
# Create a 2D Numpy array whose dtype is float32
b = np.array([[1., 0.], [2., 3.]], dtype=np.float32)
print("a constant: {}D Tensor".format(a.ndim))

c = a + b
print("a + b = \n{}".format(c))    # Display the result of a+b
# tf.matmul is matrix multiplication 
d = tf.matmul(a, b)
print("a * b = \n{}".format(d))    # Display the result of a*b

a constant: 2D Tensor
a + b = 
[[2. 2.]
 [5. 7.]]
a * b = 
[[ 5.  6.]
 [11. 12.]]


Step 6:	Tensor can be converted to Numpy

In [64]:
print(c)
print("NumpyArray:\n {}".format(c.numpy()))

tf.Tensor(
[[2. 2.]
 [5. 7.]], shape=(2, 2), dtype=float32)
NumpyArray:
 [[2. 2.]
 [5. 7.]]


---
## Keras

In TensorFlow2.0, Keras is the high-level API, so there is no need to install any additional Keras package, it can be used directly through the tf.keras API. It is highly recommended to use “tf.keras” API instead of “Keras” API because  tf.keras supports for TensorFlow operations, Eager Execution, tf.data, TPU training, and so on.

The following introduces the two most commonly methods of building the network models in Keras：
- Sequential Model 
- Function API 

### Import necessary packages

In [1]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.keras.utils import plot_model
from IPython.display import Image

### Sequential Model

Example: The model has an input with size of 28 × 28, which will be flattened into a one-dimensional vector of 784; two hidden layers (Dense layers) with ReLU activation functions; and an output followed by Softmax layer for classification.

**The first method: Using “keras.Sequential“APT in Keras**

In [2]:
# Create a Sequential model
model = keras.Sequential(name='Sequential')
# Each time model.add adds a layer to the network, the first layer needs to define the input size.
model.add(layers.Dense(64, activation='relu', input_shape=(784,)))
model.add(layers.Dense(64, activation='relu'))
# The last layer will be regarded as the output layer of the model
model.add(layers.Dense(10, activation='softmax'))

**The second method: Using “tf.keras.Sequential” API in TensorFolow2.0**

In [3]:
# all the network layers in a list and use them as parameters of tf.keras.Sequential
# And this list is also sequential, the first one needs to define the input size, and the last one is the output layer
model = tf.keras.Sequential([layers.Dense(64, activation='relu', input_shape=(784,)),
                       layers.Dense(64, activation='relu'), 
                       layers.Dense(10, activation='softmax')])

Display the network model

In [4]:
# Generate network topology. 
plot_model(model, to_file='Sequential_Model.png')

# Show the network topology. 
Image('Sequential_Model.png')

"dot" with args ['-Tps', 'C:\\Users\\hieu\\AppData\\Local\\Temp\\tmpvaphk_cr'] returned code: 1

stdout, stderr:
 b''
b'Format: "ps" not recognized. Use one of:\r\n'



AssertionError: 1

### Functional API
**1	Single Input and Output Network**

In [17]:
# Step1: Defining input layer
inputs = keras.Input(shape=(784,), name='Input')

#Step2: Connecting layers
#Hidden layers
hidden1 = layers.Dense(64, activation='relu', name='hidden1')(inputs)
hidden2 = layers.Dense(64, activation='relu', name='hidden2')(hidden1)

#Output layers
outputs = layers.Dense(10, activation='softmax', name='Output')(hidden2)

# Step 3: Creating network model
model = keras.Model(inputs=inputs, outputs=outputs)

# plot model
plot_model(model, to_file='Functional_API_Sample_Model.png')

# show model
Image('Functional_API_Sample_Model.png')

('Failed to import pydot. You must `pip install pydot` and install graphviz (https://graphviz.gitlab.io/download/), ', 'for `pydotprint` to work.')


FileNotFoundError: No such file or directory: 'Functional_API_Sample_Model.png'

FileNotFoundError: No such file or directory: 'Functional_API_Sample_Model.png'

<IPython.core.display.Image object>

**2	Multiple Inputs and single output model**

In [65]:
# Step1: Defining Input layers
img_input = keras.Input(shape=(28, 28, 1), name='Image_Input')
info_input = keras.Input(shape=(1, ), name='Information_Input')

# Step 2: connecting layers
#Hidden layers

hidden1_1 = layers.Conv2D(64, kernel_size=5, strides=2, activation='relu', name='hidden1_1')(img_input)
hidden1_2 = layers.Conv2D(32, kernel_size=5, strides=2, activation='relu', name='hidden1_2')(hidden1_1)
hidden1_2_ft= layers.Flatten()(hidden1_2)
hidden1_3 = layers.Dense(64, activation='relu', name='hidden1_3')(info_input)
concat = layers.Concatenate()([hidden1_2_ft, hidden1_3])
hidden2 = layers.Dense(64, activation='relu', name='hidden2')(concat)

# Output layer
outputs = layers.Dense(1, name='Output')(hidden2)

# Step 3: Creating network model
model = keras.Model(inputs=[img_input, info_input], outputs=outputs)

# plot model
plot_model(model, to_file='Functional_API_Multi_Input_Model.png')

# show model
Image('Functional_API_Multi_Input_Model.png')

('Failed to import pydot. You must `pip install pydot` and install graphviz (https://graphviz.gitlab.io/download/), ', 'for `pydotprint` to work.')


FileNotFoundError: No such file or directory: 'Functional_API_Multi_Input_Model.png'

FileNotFoundError: No such file or directory: 'Functional_API_Multi_Input_Model.png'

<IPython.core.display.Image object>

**3 Single input and multiple outputs Model**

In [66]:
# Step1: Defining Input layers
inputs = keras.Input(shape=(28, 28, 1), name='Input')

#Step 2: connecting layers
# Hidden layers
hidden1 = layers.Conv2D(64, kernel_size=3, activation='relu', name='hidden1')(inputs)
hidden2 = layers.Conv2D(64, kernel_size=3, strides=2, activation='relu', name='hidden2')(hidden1)
hidden3 = layers.Conv2D(64, kernel_size=3, strides=2, activation='relu', name='hidden3')(hidden2)
flatten = layers.Flatten()(hidden3) # flattening 

# Output layers
age_output = layers.Dense(1, name='Age_Output')(flatten)
gender_output = layers.Dense(1, name='Gender_Output')(flatten)

# Step 3: Creating network model 
model = keras.Model(inputs=inputs, outputs=[age_output, gender_output])

# plot model
plot_model(model, to_file='Functional_API_Multi_Output_Model.png')

# show model
Image('Functional_API_Multi_Output_Model.png')

('Failed to import pydot. You must `pip install pydot` and install graphviz (https://graphviz.gitlab.io/download/), ', 'for `pydotprint` to work.')


FileNotFoundError: No such file or directory: 'Functional_API_Multi_Output_Model.png'

FileNotFoundError: No such file or directory: 'Functional_API_Multi_Output_Model.png'

<IPython.core.display.Image object>

**4	Multiple Inputs and Multiple Outputs Network**

In [67]:
# Step1: Defining Input layers
image_inputs = keras.Input(shape=(28, 28, 1), name='Image_Input')
info_inputs = keras.Input(shape=(10, ), name='Info_Input')

#Step 2: connecting layers
#Hidden layers

hidden1 = layers.Conv2D(64, kernel_size=3, activation='relu', name='hidden1')(image_inputs)
hidden2 = layers.Conv2D(64, kernel_size=3, strides=2, activation='relu', name='hidden2')(hidden1)
hidden3 = layers.Conv2D(64, kernel_size=3, strides=2, activation='relu', name='hidden3')(hidden2)
flatten = layers.Flatten()(hidden3)

# Dense layer
hidden4 = layers.Dense(64)(info_inputs)

concat = layers.Concatenate()([flatten, hidden4])

# Output layers
weather_outputs = layers.Dense(1, name='Output1')(concat)
temp_outputs = layers.Dense(1, name='Output2')(concat)
humidity_outputs = layers.Dense(1, name='Output3')(concat)

# Step 3: Creating network model 
model = keras.Model(inputs=[image_inputs, info_inputs], 
                    outputs=[weather_outputs, temp_outputs, humidity_outputs])

# plot mode
plot_model(model, to_file='Functional_API_Multi_Input_Multi_Output_Model.png')

# show model
Image('Functional_API_Multi_Input_Multi_Output_Model.png')

('Failed to import pydot. You must `pip install pydot` and install graphviz (https://graphviz.gitlab.io/download/), ', 'for `pydotprint` to work.')


FileNotFoundError: No such file or directory: 'Functional_API_Multi_Input_Multi_Output_Model.png'

FileNotFoundError: No such file or directory: 'Functional_API_Multi_Input_Multi_Output_Model.png'

<IPython.core.display.Image object>

---
## tf.data

### Basic Functions of tf.data API

1.`tf.data.Dataset.from_tensors`: creating dataset with single element.

In [68]:
dataset = tf.data.Dataset.from_tensors(tf.constant([1, 2, 3, 4, 5, 6, 7, 8, 9, 10], shape=(10, )))
print(dataset)

<TensorDataset shapes: (10,), types: tf.int32>


2.`tf.data.Dataset.from_tensor_slices`: creating a dataset that whose elements are slices of tensors.

In [69]:
x_data = tf.data.Dataset.from_tensor_slices(tf.constant([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], shape=(10, )))
print(x_data)

y_data = tf.data.Dataset.from_tensor_slices(tf.constant([0, 2, 4, 6, 8, 10, 12, 14, 16, 18], shape=(10, )))
print(y_data)

<TensorSliceDataset shapes: (), types: tf.int32>
<TensorSliceDataset shapes: (), types: tf.int32>


3.`for loop`

In [70]:
for data in dataset:
    print(data)

tf.Tensor([ 1  2  3  4  5  6  7  8  9 10], shape=(10,), dtype=int32)


In [71]:
for data1, data2 in zip(x_data, y_data):
    print('x: {}, y: {}'.format(data1, data2))

x: 0, y: 0
x: 1, y: 2
x: 2, y: 4
x: 3, y: 6
x: 4, y: 8
x: 5, y: 10
x: 6, y: 12
x: 7, y: 14
x: 8, y: 16
x: 9, y: 18


4.`take`：creating a dataset with count elements from the source dataset

In [25]:
for data in dataset:
    print(data)

tf.Tensor([ 1  2  3  4  5  6  7  8  9 10], shape=(10,), dtype=int32)


In [26]:
for data1, data2 in zip(x_data.take(5), y_data.take(5)):
    print('x: {}, y: {}'.format(data1, data2))

x: 0, y: 0
x: 1, y: 2
x: 2, y: 4
x: 3, y: 6
x: 4, y: 8


In [72]:
for data1, data2 in zip(x_data.take(12), y_data.take(12)):
    print('x: {}, y: {}'.format(data1, data2))

x: 0, y: 0
x: 1, y: 2
x: 2, y: 4
x: 3, y: 6
x: 4, y: 8
x: 5, y: 10
x: 6, y: 12
x: 7, y: 14
x: 8, y: 16
x: 9, y: 18


5.`tf.data.Dataset.zip`

In [74]:
dataset = tf.data.Dataset.zip((x_data, y_data))
print(dataset)

<ZipDataset shapes: ((), ()), types: (tf.int32, tf.int32)>


6.`map`：transformation of data by using a specified function.

In [75]:
tf.data.Dataset.range(10).map(lambda x: x*2)

<MapDataset shapes: (), types: tf.int64>

7.Naming: the samples from dataset can be named

In [76]:
x = tf.data.Dataset.range(10)
y = tf.data.Dataset.range(10).map(lambda x: x*2)

dataset = tf.data.Dataset.zip({"x": x, "y": y})
print(dataset)

<ZipDataset shapes: {x: (), y: ()}, types: {x: tf.int64, y: tf.int64}>


In [77]:
for data in dataset.take(10):
    print('x: {}, y: {}'.format(data['x'], data['y']))

x: 0, y: 0
x: 1, y: 2
x: 2, y: 4
x: 3, y: 6
x: 4, y: 8
x: 5, y: 10
x: 6, y: 12
x: 7, y: 14
x: 8, y: 16
x: 9, y: 18


8. Set a size for each batch

In [78]:
dataset = tf.data.Dataset.zip({"x": x, "y": y}).batch(2)

for data in dataset.take(5):
    print('x: {}, y: {}'.format(data['x'], data['y']))

x: [0 1], y: [0 2]
x: [2 3], y: [4 6]
x: [4 5], y: [ 8 10]
x: [6 7], y: [12 14]
x: [8 9], y: [16 18]


9.`shuffle`：Randomly shuffling the elements of the dataset. A buffer is filled with “buffer_size” elements, then these elements in this buffer are randomly sampled, the selected elements are replaced with new elements.

In [79]:
dataset = dataset.shuffle(10)
for data in dataset.take(5):
    print('x: {}, y: {}'.format(data['x'], data['y']))

x: [2 3], y: [4 6]
x: [6 7], y: [12 14]
x: [8 9], y: [16 18]
x: [0 1], y: [0 2]
x: [4 5], y: [ 8 10]


10.`repeat`：After finishing reading all the samples from a dataset, no samples can be read unless a “repeat” function is used. Setting repeat(n) allows n times dataset to be repeated.

In [80]:
for data in dataset.take(10):
    print('x: {}, y: {}'.format(data['x'], data['y']))

    
print('-' * 50)
dataset = dataset.repeat(2)
for data in dataset.take(10):
    print('x: {}, y: {}'.format(data['x'], data['y']))

x: [8 9], y: [16 18]
x: [6 7], y: [12 14]
x: [0 1], y: [0 2]
x: [4 5], y: [ 8 10]
x: [2 3], y: [4 6]
--------------------------------------------------
x: [4 5], y: [ 8 10]
x: [8 9], y: [16 18]
x: [0 1], y: [0 2]
x: [6 7], y: [12 14]
x: [2 3], y: [4 6]
x: [6 7], y: [12 14]
x: [4 5], y: [ 8 10]
x: [2 3], y: [4 6]
x: [8 9], y: [16 18]
x: [0 1], y: [0 2]
